generation:
  ts_number: 5
  ts_size: 100
  sample_points: True
  save_data_folder: "../saved_data"
  json_name: "generation.json"
  csv_name: "values.csv"
  plot_name: "plot.png"

clustering:
  clusters: 2

linspace_info:
  linspace_parts: 100
  linspace_borders: [ 0, 1 ]
  center_shift: 1.0
  step_coeff: 0.5
  use_k: True

scheduler:
  stable_parameters: True
  single_schedule: False
  process_list: null
  process_order: null
  strict_num_parts: False

parameters_generation_method:
  aggregation_method:
    weighted_values: True
    use_max: False

process:
  simple_random_walk:
    _target_: tsg.process.simple_random_walk.SimpleRandomWalk
    init_values_coeff: 0.5
    fixed_walk: 1.0
    fixed_up_probability: 0.5
  random_walk:
    _target_: tsg.process.random_walk.RandomWalk
    init_values_coeff: 0.5
  simple_exponential_smoothing:
    _target_: tsg.process.simple_exponential_smoothing.SimpleExponentialSmoothing
    init_values_coeff: 0.5
    long_term_coeff_range: [ 0.0, 0.3 ]
  double_exponential_smoothing:
    _target_: tsg.process.double_exponential_smoothing.DoubleExponentialSmoothing
    init_values_coeff: 0.5
    long_term_coeff_range: [ 0.0, 0.3 ]
    trend_coeff_range: [ 0.0, 0.05 ]
  triple_exponential_smoothing:
    _target_: tsg.process.triple_exponential_smoothing.TripleExponentialSmoothing
    lag: 12
    long_term_coeff_range: [ 0.0, 0.3 ]
    trend_coeff_range: [ 0.0, 0.05 ]
    seasonal_coeff_range: [ 0.5, 1.0 ]
